---
title: Deepayan Bhowmik
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:month-:day-:year-:title:output_ext"
    layout: post
    author: Deepayan Bhowmik
    gists: false
safe: false
markdown: kramdown
highlighter: rouge
lsi: false
permalink: "/:title"
description: 'Deepayan Bhowmik''s personal website. 
baseurl: 
url: https://dbhowmik.github.io/
twitter_username: ditunilu
github_username: dbhowmik
accent: "#f7f7e6"
author: Lukas Himsel
address: Manegoldstraße 11<br>97346 Iphofen, DE
email: lukas@himsel.me
tel: "+49 162 363 3551"
isolang: de
exclude:
- LICENSE
- README.md
include:
- ".firebaserc"
- firebase.json
replacements:
- - "<img"
  - "<amp-img"
- - alt="" />
  - ' layout="responsive" height="300px" width="600px"></amp-img>'
- - "<video"
  - "<amp-video"
- - "</video"
  - "</amp-video"
- - <script src="https://dbhowmik.github.io/
  - <amp-gist data-gistid="
- - .js"></script>
  - '" layout="fixed-height" height="250"></amp-gist>'
- - id="amp"
  - id="a-m-p"
